export const countryCardsData = {
  title_ru: "Выберите удобную для вас страну",
  title_en: "Select your favorite country",
  title_ar: "اختر البلد",
  title_tr: "Size uygun ülkeyi seçin",
  cards: [
    {
      label_ru: "Ассортимент продукции в Турции",
      label_en: "Product range in Türkiye",
      label_ar: "المنتجات في تركيا",
      label_tr: "Türkiye ürün çeşidi",
      // label_ru: "Товары в Узбекистане",
      // label_en: "Products in Uzbekistan",
      // label_ar: "منتجات في أوزبكستان",
      // label_tr: "Ürünler Özbekistan'da",
      link: "https://novaplastik.uz/",
      country: "uz",
    },
    {
      label_ru: "Ассортимент продукции в Узбекистане",
      label_en: "Product range in Uzbekistan",
      label_ar: "المنتجات في اوزبكستان",
      label_tr: "Özbekistan ürün çeşidi",
      // label_ru: "Товары в Египте",
      // label_en: "Products in Egypt",
      // label_ar: "منتجات في مصر",
      // label_tr: "Ürünler Mısır'da",
      link: "https://eg.novaplastik.uz/",
      country: "eg",
    },
    {
      label_ru: "Ассортимент продукции в Египете",
      label_en: "Product range in Egypt",
      label_ar: "المنتجات في مصر",
      label_tr: "Mısır ürün çeşidi",
      // label_ru: "Товары в Турции",
      // label_en: "Products in Turkey",
      // label_ar: "منتجات في تركيا",
      // label_tr: "Ürünler Türkiye'de",
      link: "https://tr.novaplastik.uz/",
      country: "tr",
    },
  ],
};
